/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment01;

import java.io.File;
import java.util.Collections;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lion
 */
public class RedBoxMainMenu extends javax.swing.JFrame {

//    private List<MusicCD> listMusic = null;
//    private List<MovieCD> listMovie = null;    
    private Utils Utility = null;
    private DefaultTableModel dtmVideo = null;
    private DefaultTableModel dtmMusic = null;
    
    public BOMovieCD bMovie = null;
    public BOMusicCD bMusic = null;
    
    /**
     * Creates new form RedBoxMainMenu
     */
    public RedBoxMainMenu() {
        initComponents();
        bMovie = new BOMovieCD(); 
        bMusic = new BOMusicCD();
        Utility = new Utils();
        
        dtmMusic = new DefaultTableModel();
        dtmMusic.addColumn("Code");
        dtmMusic.addColumn("Title");
        dtmMusic.addColumn("Artist");
        dtmMusic.addColumn("Price");
        tblMusic.setModel(dtmMusic);
        
        
        dtmVideo = new DefaultTableModel();
        dtmVideo.addColumn("Code");
        dtmVideo.addColumn("Title");
        dtmVideo.addColumn("Price");
        tblVideo.setModel(dtmVideo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblVideo = new javax.swing.JTable();
        btnAddVideo = new javax.swing.JButton();
        btnSortVideo = new javax.swing.JButton();
        btnDeleteVideo = new javax.swing.JButton();
        btnImportVideo = new javax.swing.JButton();
        btnExportVideo = new javax.swing.JButton();
        cboTypeVideo = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        btnSearchVideo = new javax.swing.JButton();
        txtSearchVideo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResultVideo = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnAddMusic = new javax.swing.JButton();
        btnImportMusic = new javax.swing.JButton();
        btnExportMusic = new javax.swing.JButton();
        btnDeleteMusic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMusic = new javax.swing.JTable();
        btnSortMusic = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtSearchMusic = new javax.swing.JTextField();
        btnSearchMusic = new javax.swing.JButton();
        cboTypeMusic = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultMusic = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("Video CD management");

        tblVideo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Title", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblVideo);

        btnAddVideo.setText("Add new");
        btnAddVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVideoActionPerformed(evt);
            }
        });

        btnSortVideo.setText("Sort");
        btnSortVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortVideoActionPerformed(evt);
            }
        });

        btnDeleteVideo.setText("Delete");
        btnDeleteVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVideoActionPerformed(evt);
            }
        });

        btnImportVideo.setText("Import");
        btnImportVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportVideoActionPerformed(evt);
            }
        });

        btnExportVideo.setText("Export");
        btnExportVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportVideoActionPerformed(evt);
            }
        });

        cboTypeVideo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code", "Title", "Price" }));

        btnSearchVideo.setText("Search");
        btnSearchVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVideoActionPerformed(evt);
            }
        });

        txtResultVideo.setColumns(20);
        txtResultVideo.setRows(5);
        jScrollPane4.setViewportView(txtResultVideo);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(151, 151, 151))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSortVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSearchVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTypeVideo, 0, 73, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(btnSearchVideo)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddVideo)
                        .addGap(18, 18, 18)
                        .addComponent(btnSortVideo)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteVideo)
                        .addGap(18, 18, 18)
                        .addComponent(btnImportVideo)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportVideo)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchVideo)
                    .addComponent(cboTypeVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Video CD", jPanel2);

        btnAddMusic.setText("Add new");
        btnAddMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMusicActionPerformed(evt);
            }
        });

        btnImportMusic.setText("Import");
        btnImportMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportMusicActionPerformed(evt);
            }
        });

        btnExportMusic.setText("Export");
        btnExportMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportMusicActionPerformed(evt);
            }
        });

        btnDeleteMusic.setText("Delete");
        btnDeleteMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMusicActionPerformed(evt);
            }
        });

        tblMusic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Code", "Title", "Artist", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMusic);
        if (tblMusic.getColumnModel().getColumnCount() > 0) {
            tblMusic.getColumnModel().getColumn(2).setHeaderValue("Artist");
        }

        btnSortMusic.setText("Sort");
        btnSortMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortMusicActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Music CD management");

        btnSearchMusic.setText("Search");
        btnSearchMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMusicActionPerformed(evt);
            }
        });

        cboTypeMusic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code", "Title", "Price" }));

        txtResultMusic.setColumns(20);
        txtResultMusic.setRows(5);
        jScrollPane2.setViewportView(txtResultMusic);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAddMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSortMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearchMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTypeMusic, 0, 73, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(btnSearchMusic)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddMusic)
                        .addGap(18, 18, 18)
                        .addComponent(btnSortMusic)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteMusic)
                        .addGap(18, 18, 18)
                        .addComponent(btnImportMusic)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportMusic)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMusic)
                    .addComponent(cboTypeMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Music CD", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVideoActionPerformed
        // TODO add your handling code here:
        VideoEdit frmVideoForm = new VideoEdit(this, true);                
        
        frmVideoForm.setLocation(500, 300);
        
        String code = Utility.generateString(10);
        
        frmVideoForm.getTxtCode().setText(code);
        frmVideoForm.getTxtCode().setEditable(false);
        
        frmVideoForm.setVisible(true);        
                                                                                                                                                        
        String title = frmVideoForm.getTxtTitle().getText();
        
        try {
            double price = Double.parseDouble(frmVideoForm.getTxtPrice().getText());
            if (title != null && title.length() > 0){
                MovieCD tmp = new MovieCD(code, title, price);
                bMovie.add(tmp);
                dtmVideo.addRow(tmp.toArray());
            }
        } catch (NumberFormatException e){
            System.out.println("Price error");
        }
        
        
        
    }//GEN-LAST:event_btnAddVideoActionPerformed

    private void btnExportVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportVideoActionPerformed
        // TODO add your handling code here:
        File fileHandler = null;
        JFileChooser chooser = new JFileChooser();
        int choice = chooser.showSaveDialog(jLabel1);
        if(choice == JFileChooser.APPROVE_OPTION){
            fileHandler = chooser.getSelectedFile();
        }
        
        if(fileHandler != null){
            String filePath = fileHandler.getPath();
            bMovie.saveData(filePath);
        }   
        
        
        
    }//GEN-LAST:event_btnExportVideoActionPerformed

    private void btnImportVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportVideoActionPerformed
        // TODO add your handling code here:
        File fileHandle = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Data file", "dat"));
        int choice = chooser.showOpenDialog(jLabel1);
        if(choice == JFileChooser.APPROVE_OPTION){
            fileHandle = chooser.getSelectedFile();            
        }
        
        if(fileHandle != null){
            String filePath = fileHandle.getPath();
            bMovie.loadAll(filePath);
            clearVideoTable();

            int size = bMovie.getSize();
            for(int i = 0; i< size; i++){
                dtmVideo.addRow(bMovie.getMovie(i).toArray());
            }
        }
        
    }//GEN-LAST:event_btnImportVideoActionPerformed

    private void clearVideoTable(){
        int rows = dtmVideo.getRowCount();
        for(int i = 0; i< rows; i++){
            dtmVideo.removeRow(0);
        }
    }
    
    private void clearMusicTable(){
        int rows = dtmMusic.getRowCount();
        for(int i = 0; i < rows; i++ ){
            dtmMusic.removeRow(0);
        }
    }
    
    private void btnSortVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortVideoActionPerformed
        // TODO add your handling code here:
        
        clearVideoTable();
        
        bMovie.sortMovie();
        int size = bMovie.getSize();
        for(int i = 0; i < size; i++){
            dtmVideo.addRow(bMovie.getMovie(i).toArray());
        }
        
    }//GEN-LAST:event_btnSortVideoActionPerformed

    private void btnDeleteVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVideoActionPerformed
       
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure to delete this row?", "Confirmation", 0);        
        if(confirm == 0){
            try {
                int selectedRow = tblVideo.getSelectedRow();
                String code = tblVideo.getValueAt(selectedRow, 0).toString();
                bMovie.deleteMovie(code);

                dtmVideo.removeRow(selectedRow);
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
        
        
        
    }//GEN-LAST:event_btnDeleteVideoActionPerformed

    private void btnSearchVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVideoActionPerformed
        // TODO add your handling code here:
        int type = cboTypeVideo.getSelectedIndex();
        String query = txtSearchVideo.getText();
        String result = "";
        MovieCD tmp = null;
        switch (type){
            case 0: //search by code                
                tmp = bMovie.searchByCode(query);
                break;
            case 1: // seach by title
                tmp = bMovie.searchByTitle(query);
                break;
            case 2: // seach by price
                try {
                    tmp = bMovie.searchByPrice(Double.parseDouble(query));
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                break;
        }
        if(tmp != null){
            result += "Code: " + tmp.getCode() + "\n";
            result += "Title: " + tmp.getTitle()+ "\n";
            result += "Price: " + tmp.getPrice()+ "\n";
        }else{
            result += "Not found";
        }
        txtResultVideo.setText(result);
    }//GEN-LAST:event_btnSearchVideoActionPerformed

    private void btnAddMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMusicActionPerformed
        // TODO add your handling code here:
        MusicEdit frmMusicForm = new MusicEdit(this, true);

        String code = Utility.generateString(10);
        
        frmMusicForm.getTxtCode().setText(code);
        frmMusicForm.getTxtCode().setEditable(false);
        
        frmMusicForm.setVisible(true);        
                                                                                                                                                        
        String title = frmMusicForm.getTxtTitle().getText();
        String artist = frmMusicForm.getTxtArtist().getText();
        
        try {
            double price = Double.parseDouble(frmMusicForm.getTxtPrice().getText());
            if ((title != null && title.length() > 0) && (artist != null && artist.length() > 0)){
                MusicCD tmp = new MusicCD(code, title, artist, price);
                bMusic.add(tmp);
                dtmMusic.addRow(tmp.toArray());
            }
        } catch (NumberFormatException e){
            System.out.println("Price error");
        }
    }//GEN-LAST:event_btnAddMusicActionPerformed

    private void btnExportMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportMusicActionPerformed
        // TODO add your handling code here:
        File fileHandler = null;
        JFileChooser chooser = new JFileChooser();
        int choice = chooser.showSaveDialog(jLabel1);
        chooser.setFileFilter(new FileNameExtensionFilter("Data file", "dat"));
        if(choice == JFileChooser.APPROVE_OPTION){
            fileHandler = chooser.getSelectedFile();
        }
        
        if (fileHandler != null){
            String filePath = fileHandler.getPath();
            bMusic.saveData(filePath);
        }
        
    }//GEN-LAST:event_btnExportMusicActionPerformed

    private void btnImportMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportMusicActionPerformed
        // TODO add your handling code here:
        File fileHandle = null;
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Data file", "dat"));
        int choice = chooser.showOpenDialog(jLabel1);
        if(choice == JFileChooser.APPROVE_OPTION){
            fileHandle = chooser.getSelectedFile();            
        }
        if(fileHandle != null){
            String filePath = fileHandle.getPath();
        
        
            bMusic.loadAll(filePath);
            clearMusicTable();

            int size = bMusic.getSize();
            for(int i = 0; i< size; i++){
                dtmMusic.addRow(bMusic.getMusic(i).toArray());
            }
        }
        
    }//GEN-LAST:event_btnImportMusicActionPerformed

    private void btnSortMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortMusicActionPerformed
        // TODO add your handling code here:
        clearMusicTable();
        
        bMusic.sortMusic();
        int size = bMusic.getSize();
        for(int i = 0; i < size; i++){
            dtmMusic.addRow(bMusic.getMusic(i).toArray());
        }
    }//GEN-LAST:event_btnSortMusicActionPerformed

    private void btnDeleteMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMusicActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure to delete this row?", "Confirm to delete", 0);
        if(confirm == 0){
            try {
                int selectedRow = tblMusic.getSelectedRow();
                String code = tblMusic.getValueAt(selectedRow, 0).toString();
                bMusic.deleteMusic(code);

                dtmMusic.removeRow(selectedRow);
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
        
    }//GEN-LAST:event_btnDeleteMusicActionPerformed

    private void btnSearchMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMusicActionPerformed
        // TODO add your handling code here:
        int type = cboTypeMusic.getSelectedIndex();
        String query = txtSearchMusic.getText();
        String result = "";
        MusicCD tmp = null;
        switch (type){
            case 0: //search by code                
                tmp = bMusic.searchByCode(query);
                break;
            case 1: // seach by title
                tmp = bMusic.searchByTitle(query);
                break;
            case 2: // seach by price
                try {
                    tmp = bMusic.searchByPrice(Double.parseDouble(query));
                } catch (Exception e) {
                    System.out.println(e.toString());
                }
                break;
        }
        if(tmp != null){
            result += "Code: " + tmp.getCode() + "\n";
            result += "Title: " + tmp.getTitle()+ "\n";
            result += "Artist: " + tmp.getArtist()+ "\n";
            result += "Price: " + tmp.getPrice()+ "\n";
        }else{
            result += "Not found";
        }
        txtResultMusic.setText(result);
    }//GEN-LAST:event_btnSearchMusicActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */  
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedBoxMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedBoxMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedBoxMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedBoxMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedBoxMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMusic;
    private javax.swing.JButton btnAddVideo;
    private javax.swing.JButton btnDeleteMusic;
    private javax.swing.JButton btnDeleteVideo;
    private javax.swing.JButton btnExportMusic;
    private javax.swing.JButton btnExportVideo;
    private javax.swing.JButton btnImportMusic;
    private javax.swing.JButton btnImportVideo;
    private javax.swing.JButton btnSearchMusic;
    private javax.swing.JButton btnSearchVideo;
    private javax.swing.JButton btnSortMusic;
    private javax.swing.JButton btnSortVideo;
    private javax.swing.JComboBox cboTypeMusic;
    private javax.swing.JComboBox cboTypeVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable tblMusic;
    private javax.swing.JTable tblVideo;
    private javax.swing.JTextArea txtResultMusic;
    private javax.swing.JTextArea txtResultVideo;
    private javax.swing.JTextField txtSearchMusic;
    private javax.swing.JTextField txtSearchVideo;
    // End of variables declaration//GEN-END:variables
}
